name: Weekly download data from DataSUS

on:
  schedule:
    - cron: "0 21 * * 2" # Runs at 9:00 PM (UTC) every Tuesday

  workflow_dispatch:

jobs:
  build:
    runs-on: Ubuntu-20.04

    steps:
      - name: build-1
        uses: docker/build-push-action@v2
        run: >
          ls
        with:
          context: .
          file: download_data/Dockerfile
          push: false
          build-args: DRIVE_CREDENTIALS=${{ secrets.DRIVE_CREDENTIALS }}


