name: Weekly download data from DataSUS

on:
  schedule:
    - cron: "0 21 * * 2" # Runs at 9:00 PM (UTC) every Tuesday

  workflow_dispatch:

jobs:
  build:
    runs-on: Ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: build-1
        env:
          DRIVE_CREDENTIALS: ${{ secrets.DRIVE_CREDENTIALS }}
        run: |
          cd download_data
          ls
          docker build --build-arg DRIVE_CREDENTIALS=${DRIVE_CREDENTIALS} --no-cache .

