name: Weekly download data from DataSUS

on:
  schedule:
    - cron: "0 21 * * 2" # Runs at 9:00 PM (UTC) every Tuesday

  workflow_dispatch:

jobs:
  weekly_download_data:
    runs-on: Ubuntu-20.04
    uses: docker/build-push-action@v2
      with:
        context: .
        file: download_data/Dockerfile
        push: false
        build-args: DRIVE_CREDENTIALS=${{ secrets.DRIVE_CREDENTIALS }}