name: Run on push to main

on:
  # push:
  #   branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: Ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: build container
        env: 
          SHINY_SECRET: ${{ secrets.SHINY_SECRET }}
          SHINY_TOKEN: ${{ secrets.SHINY_TOKEN }}
        run: >
          docker build -t guipsoares/srag-monitor:latest --build-arg SHINY_TOKEN=${SHINY_TOKEN} --build-arg SHINY_SECRET=${SHINY_SECRET} --no-cache .

